name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Run formatter and linter
        continue-on-error: true
        run: |
          black --check . || true
          flake8 . --max-line-length=120 --extend-ignore=E203,W503,E501 || true

  # Note: heavy model installs (torch) are omitted from CI by default; add a
  # separate job that installs CPU wheels if you need to run full integration tests.
